//main app switches
//#define PLTT_TRACKER
//#define PLTT_TARGET
//#define PLTT_SECURE
#define UNIGE_TESTBED
//#define CTI_TESTBED
//#define UZL_TESTBED
//#define PLTT_DEMO_topology

//target properties
#ifdef PLTT_TARGET
	//#define PLTT_TARGET_MINI_RUN
	#define TRACE_DIMINISH_SECONDS 1
	#define TRACE_DIMINISH_AMOUNT 8
	#define TRACE_SPREAD_PENALTY 16
	#define TRACE_START_INTENSITY 255
	#define TARGET_SPREAD_MILIS 5000
	#define TARGET_TRANSMISSION_POWER -30
#ifdef PLTT_TARGET_MINI_RUN
	#define TARGET_MINI_RUN_TIMES 1
#endif
	#ifdef PLTT_SECURE
		#define TARGET_SECURE_REQUEST_ID_1 0x1111
		#define TARGET_SECURE_REQUEST_ID_2 0x2222
		#define TARGET_SECURE_REQUEST_ID_3 0x3333
		#define TARGET_SECURE_REQUEST_ID_4 0x4444
		#define TARGET_SECURE_REQUEST_ID_5 0x5555
	#endif
#endif

//tracker properties
#ifdef PLTT_TRACKER
	#define TARGET_ID_TO_TRACK1 0x1c99
	#define TARGET_TO_TRACK_MAX_INTENSITY1 127
	#define TRACKER_TRANSMISSION_POWER1 0
	#define TRACKER_SEND_MILIS1 5000
	#define TRACKER_TRACKING_METRICS_TIMER 10000
#endif

//general properties
#define MAX_NEIGHBORS_SUPPORTED 25
#define MAX_TARGETS_SUPPORTED 10
#define MAX_TRACKERS_SUPPORTED 10
#define MAX_RELIABLE_AGENTS_SUPPORTED 30
#define INTENSITY_DETECTION_THRESHOLD 240
#define PLTT_APP_CHANNEL 20
#define BACKOFF_CONNECTIVITY_WEIGHT 500
#define BACKOFF_LQI_WEIGHT 1
#define BACKOFF_RANDOM_WEIGHT 300
#define BACKOFF_CANDIDATE_LIST_WEIGHT 1000
#define NB_CONVERGENCE_TIME 60000
#define DECRYPTION_REQUEST_TIMER 1000
#define DECRYPTION_REQUEST_OFFSET 50
#define PROACTIVE_INHIBITION_TIMER 1000
#define MAX_SECURE_TRACES_SUPPORTED 25
#define DECRYPTION_MAX_RETRIES 5
#define ERASE_DAEMON_TIMER 100
#define TRANSMISSION_POWER_DB -12
#define RANDOM_ENABLE_TIMER_RANGE 2000

//metrics timeout
#define METRICS_TIMEOUT 2000

//opt reliable tracking properties
#define RELIABLE_TRACKING_EXPIRATION_TIME 2000
#define RELIABLE_TRACKING_RECURRING_TIME 500
#define RELIABLE_TRACKING_DAEMON_TIME 500

//secure properties
#define PLTT_SECURE_MAX_CALLBACKS
#define PLTT_SECURE_MAX_RECEIVERS

typedef uint16_t CoordinatesNumber;
typedef uint8_t IntensityNumber;
typedef uint8_t TimesNumber;
typedef uint8_t SecondsNumber;

