#define UNIGE_TESTBED
//#define TARGET_NODE
#define PASSIVE_TRACKER_NODE
#define PASSIVE_TRACKER_TRANSMISSION_DB -24
#define TARGET_TRANSMISSION_DB -30
#define TARGET_SPREAD_MILIS 1000
#define MAX_DETECTIONS 300
