#define RR_MAX_BUFFERED_MESSAGES 3
#define RR_MAX_PROTOCOLS_REGISTERED 2
#define RR_MAX_MESSAGES_PER_PROTOCOL 3
#define RR_DAEMON_PERIOD 500
#define RR_ALIVE_DAEMON_PERIOD_500
#define RR_PROTOCOL_SETTING_PERIOD 1000
#define RR_PROTOCOL_SETTING_ALIVE_PERIOD 1000
