#define MAX_PG_PAYLOAD 30
#define ECHO_MAX_NODES 60
#define DEBUG_ECHO
#define ENABLE_LQI_THRESHOLDS
#define ENABLE_STABILITY_THRESHOLDS
#define CALCULATE_INVERSE_STABILITY
#define ECHO_TIMES_ACC_NEARBY 2
#define SUNSPOT_TEST
