//default NB protocol settings
#define NB_MAX_NEIGHBORS 50
#define NB_MAX_REGISTERED_PROTOCOLS 10
#define NB_BEACON_PERIOD 1000
#define NB_CHANNEL 0
#define NB_TRANSMISSION_POWER_DB 0
#define NB_RELAX_MILLIS 100

//default registered protocol settings
#define NB_MAX_AVG_LQI_THRESHOLD 255
#define NB_MIN_AVG_LQI_THRESHOLD 0
#define NB_MAX_AVG_LQI_INVERSE_THRESHOLD 255
#define NB_MIN_AVG_LQI_INVERSE_THRESHOLD 0
#define NB_MAX_LINK_STAB_RATIO_THRESHOLD 100
#define NB_MIN_LINK_STABILITY_RATIO_THRESHOLD 0
#define NB_MAX_LINK_STAB_RATIO_INVERSE_THRESHOLD 100
#define NB_MIN_LINK_STAB_RATIO_INVERSE_THRESHOLD 0
#define NB_CONSECUTIVE_BEACONS_THRESHOLD 5
#define NB_CONSECUTIVE_BEACONS_LOST_THRESHOLD 5
#define NB_MAX_PROTOCOL_PAYLOAD_SIZE 50
#define NB_PROPOSED_TRANSMISSION_POWER_DB -6
#define NB_PROPOSED_TRANSMISSION_POWER_DB_WEIGHT 10
#define NB_PROPOSED_BEACON_PERIOD 1000
#define NB_PROPOSED_BEACON_PERIOD_WEIGHT 10
#define NB_PAYLOAD_OFFSET 0



